language: python
python:
  - "2.7"

install:
  - pushd /tmp
  - git clone https://github.com/tabatkins/bikeshed.git
  - pip install --editable $PWD/bikeshed
  - bikeshed update
  - popd

script:
  - ./scripts/build-doc.sh

before_deploy:
  - rm .gitignore

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: ./doc
  committer_from_gh: true
  name: weso-bot
  email: thewilly.work@gmail.com
  on:
    branch:
      shex-lite-2.0-dev

branches:
  except:
    - gh-pages
